name: TrafficPlot Auto Generation

on:
  schedule:
    - cron: '0 * * * *'  # 每天UTC时间的 5:00, 8:00, 11:00, 14:00（对应美东时间的 0:00, 3:00, 6:00, 9:00）
  workflow_dispatch:  # 允许手动触发工作流
jobs:
  generate_image:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 给 Actions 写入权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 拉取仓库代码

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # 设置 Python 环境

      - name: Install PyGithub version 2.5.0
        run: pip install PyGithub==2.5.0  # 安装指定版本

      - name: Install dependencies
        run: |
          pip3 install pandas matplotlib PyGithub pillow

      - name: Run image generation script
        run: python3 TrafficPlot/GithubTrafficPlot.py ${{ secrets.GITHUBTRAFFICPLOT }} TrafficPlot/RepoName.txt TrafficPlot/   # 执行 Python 脚本，生成图片

      - name: Commit and push generated image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          
          git add -f ./*_TrafficPlot.png ./TrafficPlot/*.csv  # 添加图片
          git commit -m "Auto-generated TrafficPlot.png and PlotData.csv" || echo "No changes to commit"
          git pull --rebase # 拉取最新的代码，避免冲突
          
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
